### ISSUE TITLE
Contact search not working for any part of the name.

### ISSUE THREAD

**Issue by Merurino** [psi-im/psi#178]
Hello, in the previous versions of PSI I was able to search for a term and it would search for all contacts that *contain* this term. However in this last version the search only search for contacts that *begin with* this term. 

I believe a flag to configure that would be of extreme importance.

**Comment by raid1** [comment]
I second this.

**Comment by wadealer** [comment]
What version are you use? This was fixed a long time ago with this commit https://github.com/psi-im/psi/commit/2b6b500ed98310b6ee36c0b59da3b705aa0657ce

**Comment by Merurino** [comment]
I am using version 0.15, which I believe is the most recent one, and the problem still persists.

**Comment by wadealer** [comment]
The most resent is the version compilled from sources.

**Comment by Merurino** [comment]
Ok, I don't know how to compile this, the developer wiki (where I would probably have information about it) appears not to be working. Can you point me where could I find instructions to do that?

Thanks a lot.
