### ISSUE TITLE
Empty plugin toolbar actions (chat/groupchat)

### ISSUE THREAD

**Issue by Neustradamus** [psi-im/psi#563]
Empty plugin toolbar actions (chat/groupchat):
- https://i.ibb.co/P56Mqy9/psi-options-toolbar-missing-plugins-actions.png

**Comment by tehnick** [comment]
@Neustradamus You should write Psi+ version in such bug reports.

**Comment by Neustradamus** [comment]
@tehnick: Your last build :)

**Comment by tehnick** [comment]
@Neustradamus 
This is not an answer! This is a bug tracker but not our groupchat. So you should write precise information here which can be used at any time. No-one will look to list of my (or any other) builds for comparing dates and versions.

> Your last build :)

Such useless messages from you (plus their huge amount) already caused to that some developers stopped reading emails from GitHub (at least for activity in Psi/Psi+ projects).

**Comment by Neustradamus** [comment]
@tehnick: 1.4.1275 (2020-05-21, Psi:8ce049f8, Psi+:2170e90)

Because they think that there is no problem, but maybe they do not use this XMPP client :)

**Comment by tehnick** [comment]
I have found that this bug was introduced in Psi+ 1.4.1237:
https://github.com/psi-plus/psi-plus-snapshots/commit/5d76699c

This commit broke toolbar settings:
https://github.com/psi-im/plugins/commit/7f17169

**Comment by tehnick** [comment]
Fixed in Psi+ 1.4.1303 and newer.

**Comment by Neustradamus** [comment]
@Ri0n, @tehnick: Thanks but it is not solved and it bugs a lot!

Before the empty bug:
- All plugin actions was listed (disabled and enabled plugins)
- Actions could be enabled if the plugin is disabled but not showed in toolbar (only showed if plugin is enabled)
- Icon from toolbars is automatically added if plugin is enabled or action added
- Icon from toolbars is automatically removed if plugin is disabled or action disabled
- If we enable a plugin it is instantaneous (not needed to close "Options" or close the client and reopen)
- If we disable a plugin it is instantaneous (not needed to close "Options" or close the client and reopen)

Currently:
1/ Disabled plugin actions are not listed
2/ If we enable a plugin, the action is not added in the list, we must to close "Options" and reopen it.
3/ If we disable a plugin which has an action (chat tab for example), when we go in "Toolbars", Psi crashs
4/ When plugins are disabled, no listed actions and not in enabled section

You can test with Chess / Gomoku / OMEMO / OTR / etc.

**Comment by tehnick** [comment]
> Before the empty bug:

Before changing mechanism of receiving of meta-information from plugins. The main idea was: do not load+unload unused plugins for this, but read meta-information from plugin files instead.

> * All plugin actions was listed (disabled and enabled plugins)

Yep, this was convenient.

@Ri0n could it be done with current architecture?

> 3/ If we disable a plugin which has an action (chat tab for example), when we go in "Toolbars", Psi crashs

No comments...

> 5/ Toolbars are not up-to-date, we need to restart the client (linked to an old solved bug)

Yes, this is a one more regression. And serious one.

@Neustradamus 
This comment is really useful. Continue in the same spirit.

**Comment by Ri0n** [comment]
toolbar buttons for disabled plugins are rather confusing than convenient.
I'll review the rest later.

**Comment by tehnick** [comment]
> toolbar buttons for disabled plugins are rather confusing than convenient.

Then at least:
* List of available plugins and list of used actions should be updated each time when Toolbar Options tab is activated.
* The position of plugins actions in a list of used actions should be stored despite their status (enabled or disabled). To not force users update toolbars settings each time after disabling and enabling of plugin.

**Comment by Neustradamus** [comment]
I had forgotten and I have edited:
- 6/ When we disable a plugin, and close "Options" and after reopen, the plugin is always enabled, we need to restart the client

**Comment by Ri0n** [comment]
> 1/ Disabled plugin actions are not listed (in action list and current list)

As I said it's kind of confusing to add kind of not existing stuff on the toolbar. Even so already added items are not removed now and therefore error-prone

> 2/ If we enable a plugin, the action is not added in the list, we must to close "Options" and reopen it.

fixed

> 3/ If we disable a plugin which has an action (chat tab for example), when we go in "Toolbars", Psi crashs

fixed

> 4/ When plugins are disabled, nothing in listed actions and not listed in current actions

see 1. "error-prone" 

> 5/ Toolbars are not up-to-date, we need to restart the client (linked to an old solved bug)

in progress

> 6/ When we disable a plugin, and close "Options" and after reopen, the plugin is always enabled, we need to restart the client

not reproducible

**Comment by Ri0n** [comment]
I'll open another task for 5. everything else if fixed

**Comment by Neustradamus3** [comment]
@Ri0n: Thanks but it is not complete solved!

For 6/

Psi -> Options -> Plugins -> Gomoku -> enable
Close the window

Psi -> Options -> Plugins -> Gomoku -> disable
Close the window

Psi -> Options -> Plugins -> Gomoku -> it is always enabled
Restart the client

Temporary solution: Psi -> Options -> Plugins -> Gomoku -> it is now disabled

Can you solve it?

**Comment by Ri0n** [comment]
no idea. I tested with the latest version with two different profiles and it worked perfectly
